version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/goreleaser/fileglob
    versions:
    - 1.1.1
  - dependency-name: github.com/golangci/golangci-lint
    versions:
    - 1.37.0
    - 1.37.1
  - dependency-name: github.com/stretchr/testify
    versions:
    - 1.7.0
